package com.SAMUDRA.messaging_system.Service;

import com.SAMUDRA.messaging_system.DAO.Chat;
import com.SAMUDRA.messaging_system.DAO.ChatMessage;
import com.SAMUDRA.messaging_system.DAO.User;
import com.SAMUDRA.messaging_system.DTO.MessageRequest;
import com.SAMUDRA.messaging_system.DTO.MessageResponse;
import com.SAMUDRA.messaging_system.Exception.ChatException;
import com.SAMUDRA.messaging_system.Exception.MessageException;
import com.SAMUDRA.messaging_system.Exception.UserException;
import com.SAMUDRA.messaging_system.Mapper.MessageMapper;
import com.SAMUDRA.messaging_system.Repo.ChatParticipantRepo;
import com.SAMUDRA.messaging_system.Repo.ChatRepo;
import com.SAMUDRA.messaging_system.Repo.MessageRepo;
import com.SAMUDRA.messaging_system.Repo.UserRepo;
import com.SAMUDRA.messaging_system.enums.MessageStatus;
import com.SAMUDRA.messaging_system.enums.MessageType;
import com.SAMUDRA.messaging_system.enums.ParticipantChatStatus;
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.DisplayNameGenerator;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
class MessageServiceImplementationTest {

    @Mock
    private MessageRepo messageRepo;

    @Mock
    private ChatRepo chatRepo;

    @Mock
    private UserRepo userRepo;

    @Mock
    private ChatParticipantRepo chatParticipantRepo;

    @Mock
    private MessageMapper messageMapper;

    @InjectMocks
    private MessageServiceImplementation messageService;

    @Captor
    private ArgumentCaptor<ChatMessage> messageCaptor;

    @Test
    void sendMessage_savesAndReturnsResponse_whenValid() throws Exception {
        Chat chat = new Chat();
        // chatId is generated by JPA, tests can rely on DTO mapping instead

        User sender = new User();
        sender.setId(5L);
        sender.setUsername("eve");

        when(chatRepo.findById(200L)).thenReturn(Optional.of(chat));
        when(userRepo.findById(5L)).thenReturn(Optional.of(sender));
        when(chatParticipantRepo.findByChatChatIdAndUserId(200L, 5L)).thenReturn(Optional.of(new com.SAMUDRA.messaging_system.DAO.ChatParticipant()));

        MessageRequest req = new MessageRequest(" Hello world ", null, null);

        ChatMessage saved = new ChatMessage();
         saved.setChat(chat);
         saved.setSenderId(5L);
         saved.setSenderUsername("eve");
         saved.setContent("Hello world");
         saved.setMessageType(MessageType.TEXT);
         saved.setMessageStatus(MessageStatus.SENT);
         saved.setCreatedAt(LocalDateTime.now());

        when(messageRepo.save(any(ChatMessage.class))).thenReturn(saved);

        MessageResponse resp = new MessageResponse();
        resp.setMessageId(300L);
        when(messageMapper.mapToResponse(saved)).thenReturn(resp);

        MessageResponse result = messageService.sendMessage(200L, 5L, req);

        assertThat(result).isNotNull();
        assertThat(result.getMessageId()).isEqualTo(300L);

        verify(messageRepo).save(messageCaptor.capture());
        ChatMessage captured = messageCaptor.getValue();
        assertThat(captured.getContent()).isEqualTo("Hello world");
        assertThat(captured.getSenderId()).isEqualTo(5L);
    }

    @Test
    void sendMessage_throws_whenContentBlank() {
        MessageRequest req = new MessageRequest("   ", null, null);

        assertThrows(MessageException.class, () -> messageService.sendMessage(1L, 1L, req));
    }

    @Test
    void editMessage_updatesAndReturns_whenSenderAndNotDeleted() throws Exception {
        ChatMessage msg = new ChatMessage();
        msg.setMessageId(400L);
        msg.setSenderId(9L);
        msg.setDeleted(false);
        msg.setContent("old");

        when(messageRepo.findById(400L)).thenReturn(Optional.of(msg));

        MessageResponse resp = new MessageResponse();
        resp.setMessageId(400L);
        when(messageMapper.mapToResponse(msg)).thenReturn(resp);

        MessageResponse out = messageService.editMessage(400L, 9L, " new ");

        assertThat(msg.getContent()).isEqualTo("new");
        assertThat(msg.isEdited()).isTrue();
        assertThat(out.getMessageId()).isEqualTo(400L);
    }

    @Test
    void deleteMessage_marksDeleted_whenSenderAndNotDeleted() throws Exception {
        ChatMessage msg = new ChatMessage();
        msg.setMessageId(500L);
         msg.setSenderId(11L);
         msg.setDeleted(false);
         msg.setContent("secret");

        when(messageRepo.findById(500L)).thenReturn(Optional.of(msg));

        messageService.deleteMessage(500L, 11L);

        assertThat(msg.isDeleted()).isTrue();
        assertThat(msg.getContent()).isEqualTo("This message was deleted");
    }

    @Test
    void markAsRead_callsRepoMethod_whenParticipantValid() throws Exception {
        when(chatRepo.findById(10L)).thenReturn(Optional.of(new Chat()));
        when(chatParticipantRepo.findByChatChatIdAndUserId(10L, 2L)).thenReturn(Optional.of(new com.SAMUDRA.messaging_system.DAO.ChatParticipant()));

        messageService.markAsRead(10L, 2L);

        verify(messageRepo).markMessagesAsRead(10L, 2L);
    }

    @Test
    void forwardMessage_savesForwardedMessage_whenAllValid() throws Exception {
        ChatMessage original = new ChatMessage();
        original.setMessageId(700L);
         original.setContent("forward me");
         original.setMessageType(MessageType.TEXT);

         when(messageRepo.findById(700L)).thenReturn(Optional.of(original));

         when(chatParticipantRepo.findByChatChatIdAndUserId(1L, 6L)).thenReturn(Optional.of(new com.SAMUDRA.messaging_system.DAO.ChatParticipant()));
         when(chatParticipantRepo.findByChatChatIdAndUserId(2L, 6L)).thenReturn(Optional.of(new com.SAMUDRA.messaging_system.DAO.ChatParticipant()));

         Chat toChat = new Chat();
         when(chatRepo.findById(2L)).thenReturn(Optional.of(toChat));

         User user = new User();
         user.setId(6L);
         user.setUsername("frank");
         when(userRepo.findById(6L)).thenReturn(Optional.of(user));

         when(messageRepo.save(any(ChatMessage.class))).thenAnswer(invocation -> invocation.getArgument(0));

         messageService.forwardMessage(700L, 1L, 2L, 6L);

         verify(messageRepo, atLeastOnce()).save(any(ChatMessage.class));
     }

 }
